import React, { useState } from 'react';
import DashboardLayout from '../../components/DashboardLayout'; 
import Header from '../../components/Header/header'; 
import './reports.css';

/* SVG Icons for Modal */
const IconReport = () => <svg width="18" height="18" fill="currentColor" viewBox="0 0 24 24"><path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z"/></svg>;
const IconSearch = ({ className }) => <svg className={className} width="14" height="14" fill="currentColor" viewBox="0 0 24 24"><path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/></svg>;
const IconFilter = () => <svg width="14" height="14" fill="currentColor" viewBox="0 0 24 24"><path d="M10 18h4v-2h-4v2zM3 6v2h18V6H3zm3 7h12v-2H6v2z"/></svg>;
const IconFolder = () => <svg width="14" height="14" fill="currentColor" viewBox="0 0 24 24"><path d="M20 6h-8l-2-2H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2zm0 12H4V8h16v10z"/></svg>;
const IconNote = () => <svg width="14" height="14" fill="currentColor" viewBox="0 0 24 24"><path d="M14 2H6c-1.1 0-1.99.9-1.99 2L4 20c0 1.1.89 2 1.99 2H18c1.1 0 2-.9 2-2V8l-6-6zm2 16H8v-2h8v2zm0-4H8v-2h8v2zm-3-5V3.5L18.5 9H13z"/></svg>;
const IconRocket = () => <svg width="14" height="14" fill="currentColor" viewBox="0 0 24 24"><path d="M13.13 22.19l-1.63-3.83c3.22-1.33 5.56-4.22 6.09-7.72l-3.32 1.42 1.34-3.14 4.54-1.94c-.69-3.9-3.7-7-7.66-7.85l-1.89 4.41-3.23-1.38 1.84-4.29C4.54 3.03 1 7.42 1 12.65c0 5.4 4.22 9.81 9.54 10.1l1.1-2.58 3.12 1.34-1.63 3.83c4.13-1.36 7.28-4.8 8.16-9.03l-4.52 1.93 1.35-3.15-3.3 1.41c-.53 3.51-2.88 6.42-6.11 7.76zM11 11c-.55 0-1-.45-1-1s.45-1 1-1 1 .45 1 1-.45 1-1 1zm0 2c-1.65 0-3-1.35-3-3s1.35-3 3-3 3 1.35 3 3-1.35 3-3 3z"/></svg>;

/* MOCK DATA - Main Page */
const quickReports = [
  { icon: "📄", title: "Attendance summary", sub: "Daily, weekly & monthly", color: "blue" },
  { icon: "📊", title: "Academic performance", sub: "By grade, subject & section", color: "green" },
  { icon: "💰", title: "Fee collection", sub: "Monthly breakdowns & arrears", color: "yellow" },
  { icon: "🏆", title: "Exam results", sub: "Term / Mid-term analysis", color: "red" },
  { icon: "👨‍🏫", title: "Teacher performance", sub: "Leave, classes & feedback", color: "purple" },
  { icon: "📈", title: "Enrollment stats", sub: "New admissions vs leavers", color: "blue" },
  { icon: "⬇️", title: "Full data export", sub: "All records (XLS / CSV)", color: "green" },
  { icon: "⚠️", title: "At-risk students", sub: "Low attendance or failing", color: "red" }
];

const snapshotData = [
  { label: "Admissions", val: "88%", color: "blue" },
  { label: "Fee paid", val: "94%", color: "green" },
  { label: "Exams cleared", val: "82%", color: "blue" },
  { label: "Assignments", val: "78%", color: "yellow" },
  { label: "Events part.", val: "65%", color: "blue" },
];

const trendAttendance = [
  { label: "September", val: "94%", color: "blue" },
  { label: "October", val: "96%", color: "blue" },
  { label: "November", val: "92%", color: "yellow" },
  { label: "December", val: "88%", color: "yellow" },
  { label: "January", val: "95%", color: "blue" },
  { label: "February", val: "91%", color: "blue" },
  { label: "March", val: "97%", color: "green" },
  { label: "April", val: "93%", color: "blue" }
];

const trendFees = [
  { label: "September", val: "85%", color: "blue" },
  { label: "October", val: "88%", color: "blue" },
  { label: "November", val: "82%", color: "yellow" },
  { label: "December", val: "94%", color: "green" },
  { label: "January", val: "90%", color: "blue" },
  { label: "February", val: "87%", color: "blue" },
  { label: "March", val: "92%", color: "blue" },
  { label: "April", val: "95%", color: "green" }
];

const academicTable = [
  { grade: "Grade 10", students: 64, att: 92, attColor: "good", fee: 95, best: "Physics", worst: "Maths", trend: "Improving", tColor: "up" },
  { grade: "Grade 9", students: 142, att: 88, attColor: "avg", fee: 90, best: "English", worst: "Science", trend: "Stable", tColor: "flat" },
  { grade: "Grade 8", students: 135, att: 81, attColor: "poor", fee: 85, best: "Urdu", worst: "Maths", trend: "Declining", tColor: "down" },
  { grade: "Grade 7", students: 156, att: 95, attColor: "good", fee: 92, best: "Maths", worst: "History", trend: "Improving", tColor: "up" },
  { grade: "Grade 6", students: 148, att: 89, attColor: "avg", fee: 88, best: "Science", worst: "English", trend: "Stable", tColor: "flat" }
];

const recentReports = [
  { icon: "📄", name: "Attendance export (April 2026)", info: "Generated by SA • 10 mins ago", status: "Ready" },
  { icon: "💰", name: "Fee collection — March 2026", info: "Auto • April 1, 9:00 AM", status: "Ready" },
  { icon: "⚠️", name: "At-Risk students — Term 1", info: "Generated by SA • Yesterday", status: "Ready" },
  { icon: "❌", name: "Mid-Term results — G10", info: "Failed to generate • System error", status: "Failed" },
];

const atRiskStudents = [
  { name: "Omar Farooq", grade: "Gr 3", risk: "High", riskClass: "risk-high", abs: "15%", status: "Intervened" },
  { name: "Kashif Ali", grade: "Gr 8", risk: "High", riskClass: "risk-high", abs: "22%", status: "Action required" },
  { name: "Zara Sheikh", grade: "Gr 5", risk: "Medium", riskClass: "risk-med", abs: "10%", status: "Monitoring" },
  { name: "Bilal Raza", grade: "Gr 5", risk: "Medium", riskClass: "risk-med", abs: "12%", status: "Action required" },
];

/* MOCK DATA - Modal Report Types */
const modalReportTypes = [
  { id: 'attendance', icon: '📋', title: 'Attendance summary', desc: 'Daily, weekly, or monthly attendance for a class or full school' },
  { id: 'academic', icon: '📊', title: 'Academic performance', desc: 'Grades, averages, and rankings by student, class, or subject' },
  { id: 'fees', icon: '💰', title: 'Fee collection', desc: 'Monthly fee status, pending payments, and collection totals' },
  { id: 'exams', icon: '📝', title: 'Exam results', desc: 'Pass / fail analysis, grade distribution, and rankings per exam' },
  { id: 'teachers', icon: '👨‍🏫', title: 'Teacher performance', desc: 'Class averages, attendance marked, and assignments graded' },
  { id: 'risk', icon: '⚠️', title: 'At-risk students', desc: 'Students with low attendance or failing grades flagged for review' },
  { id: 'enrollment', icon: '🏫', title: 'Enrollment report', desc: 'New admissions, withdrawals, and current enrollment by grade' },
  { id: 'full', icon: '🗃️', title: 'Full data export', desc: 'All school records as a structured CSV for external use' }
];

export default function Reports() {
  // 👇 Modal & Toggles State 👇
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedReport, setSelectedReport] = useState('full');
  const [exportFormat, setExportFormat] = useState('PDF');
  
  const [incLogo, setIncLogo] = useState(false);
  const [incCharts, setIncCharts] = useState(false);
  const [emailAdmin, setEmailAdmin] = useState(false);
  const [schedRecurring, setSchedRecurring] = useState(false);

  return (
    <DashboardLayout 
      userRole="admin" 
      currentPath="/reports" 
      userName="System Admin" 
      userInitials="SA"
    >
      {/* 1. Fixed Page Header */}
      <div className="rep-page-header">
        <div className="rep-header-left">
          <h2>Reports</h2>
          <p>Generate, view and export comprehensive school data</p>
        </div>
        <div className="rep-header-right">
          {/* 👇 Trigger Modal 👇 */}
          <button className="rep-btn-primary" onClick={() => setIsModalOpen(true)}>
            Generate report
          </button>
          <div className="rep-avatar">SA</div>
        </div>
      </div>

      {/* 2. Fixed Command Bar */}
      <Header />

      {/* 3. INTERNAL SCROLL WRAPPER */}
      <div className="rep-scroll-wrapper">
        
        <div className="rep-grid-top">
          <div className="rep-card">
            <h3 className="rep-card-title">Quick reports</h3><br />
            <div className="rep-quick-grid">
              {quickReports.map((r, i) => (
                <div key={i} className="rep-quick-item" onClick={() => setIsModalOpen(true)}>
                  <div className={`rep-quick-icon ${r.color}`}>{r.icon}</div>
                  <div className="rep-quick-text">
                    <h4>{r.title}</h4>
                    <p>{r.sub}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            <div className="rep-card">
              <h3 className="rep-card-title">School-wide snapshot (April 2026)</h3><br />
              <div>
                {snapshotData.map((item, i) => (
                  <div className="rep-bar-row" key={i}>
                    <span className="rep-bar-label">{item.label}</span>
                    <div className="rep-bar-track">
                      <div className={`rep-bar-fill ${item.color}`} style={{ width: item.val }}></div>
                    </div>
                    <span className="rep-bar-val">{item.val}</span>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="rep-card" style={{ flexGrow: 1 }}>
              <h3 className="rep-card-title">Scheduled reports</h3><br />
              <div className="rep-sched-list">
                <div className="rep-sched-item">
                  <div className="rep-sched-day">Monday</div>
                  <div className="rep-sched-info">
                    <h4>Attendance summary</h4>
                    <p>Sent to: Principal, Coordinators</p>
                  </div>
                </div>
                <div className="rep-sched-item">
                  <div className="rep-sched-day">Friday</div>
                  <div className="rep-sched-info">
                    <h4>Fee collection weekly</h4>
                    <p>Sent to: Admin, Finance dept</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="rep-grid-mid">
          <div className="rep-card">
            <h3 className="rep-card-title">Attendance trend (2025-26)</h3><br />
            <div>
              {trendAttendance.map((item, i) => (
                <div className="rep-bar-row" key={i}>
                  <span className="rep-bar-label">{item.label}</span>
                  <div className="rep-bar-track">
                    <div className={`rep-bar-fill ${item.color}`} style={{ width: item.val }}></div>
                  </div>
                  <span className="rep-bar-val">{item.val}</span>
                </div>
              ))}
            </div>
          </div>
          <div className="rep-card">
            <h3 className="rep-card-title">Fee collection trend (2025-26)</h3><br />
            <div>
              {trendFees.map((item, i) => (
                <div className="rep-bar-row" key={i}>
                  <span className="rep-bar-label">{item.label}</span>
                  <div className="rep-bar-track">
                    <div className={`rep-bar-fill ${item.color}`} style={{ width: item.val }}></div>
                  </div>
                  <span className="rep-bar-val">{item.val}</span>
                </div>
              ))}
            </div>
          </div>
          <div className="rep-card">
            <h3 className="rep-card-title">Exam pass rate trend</h3><br />
            <div>
              {trendAttendance.slice(0, 5).map((item, i) => (
                <div className="rep-bar-row" key={i}>
                  <span className="rep-bar-label">Term {i+1}</span>
                  <div className="rep-bar-track">
                    <div className={`rep-bar-fill ${item.color}`} style={{ width: item.val }}></div>
                  </div>
                  <span className="rep-bar-val">{item.val}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="rep-card">
          <h3 className="rep-card-title">Academic performance by grade — Mid Term</h3>
          <div className="rep-table-wrapper">
            <table className="rep-table">
              <thead>
                <tr>
                  <th>Grade</th>
                  <th>Students</th>
                  <th>Avg Attendance</th>
                  <th>Avg Fee Paid</th>
                  <th>Best Subject</th>
                  <th>Weakest Subject</th>
                  <th>Overall Trend</th>
                </tr>
              </thead>
              <tbody>
                {academicTable.map((row, i) => (
                  <tr key={i}>
                    <td style={{ fontWeight: 700 }}>{row.grade}</td>
                    <td>{row.students}</td>
                    <td>
                      <div className="rep-inline-bar-wrapper">
                        <div className="rep-inline-bar-track">
                          <div className={`rep-inline-bar-fill ${row.attColor}`} style={{ width: `${row.att}%` }}></div>
                        </div>
                        <span>{row.att}%</span>
                      </div>
                    </td>
                    <td>{row.fee}%</td>
                    <td>{row.best}</td>
                    <td>{row.worst}</td>
                    <td><span className={`rep-trend-tag ${row.tColor}`}>{row.trend}</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div className="rep-grid-bottom">
          <div className="rep-card">
            <h3 className="rep-card-title">Recent reports</h3>
            <div className="rep-recent-list">
              {recentReports.map((rep, i) => (
                <div className="rep-recent-item" key={i}>
                  <div className="rep-recent-left">
                    <div className={`rep-quick-icon ${rep.status === 'Ready' ? 'green' : 'red'}`}>{rep.icon}</div>
                    <div className="rep-recent-info">
                      <h4>{rep.name}</h4>
                      <p>{rep.info}</p>
                    </div>
                  </div>
                  <div className="rep-recent-actions">
                    <span className={`rep-pill ${rep.status === 'Ready' ? 'ready' : 'failed'}`}>{rep.status}</span>
                    {rep.status === 'Ready' && <button className="rep-btn-dl">Download</button>}
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="rep-card">
            <h3 className="rep-card-title">⚠️ At-risk students</h3>
            <div className="rep-table-wrapper">
              <table className="rep-table">
                <thead>
                  <tr>
                    <th>Student</th>
                    <th>Grade</th>
                    <th>Risk Factor</th>
                    <th>Absences</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {atRiskStudents.map((stu, i) => (
                    <tr key={i}>
                      <td style={{ fontWeight: 600 }}>{stu.name}</td>
                      <td>{stu.grade}</td>
                      <td><span className={`rep-pill ${stu.riskClass}`}>{stu.risk}</span></td>
                      <td style={{ color: '#ef4444', fontWeight: 600 }}>{stu.abs}</td>
                      <td><span className="rep-btn-dl">{stu.status}</span></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>

      {/* =========================================
          ✨ GENERATE REPORT MODAL ✨
          ========================================= */}
      {isModalOpen && (
        <div className="rep-modal-overlay">
          <div className="rep-modal">
            
            {/* Modal Header */}
            <div className="rep-modal-header">
              <div className="rep-modal-title-group">
                <div className="rep-modal-icon"><IconReport /></div>
                <div className="rep-modal-title">
                  <h2>Generate Report</h2>
                  <p>Configure and export a school report in PDF or Excel</p>
                </div>
              </div>
              <div className="rep-badge-pill">Quick export</div>
            </div>

            {/* Modal Body */}
            <div className="rep-modal-body">
              
              {/* SECTION 1: REPORT TYPE */}
              <div>
                <div className="rep-section-title"><IconFolder /> SELECT REPORT TYPE <span>*</span></div>
                <div className="rep-type-grid">
                  {modalReportTypes.map(type => (
                    <div 
                      key={type.id} 
                      className={`rep-type-card ${selectedReport === type.id ? 'active' : ''}`}
                      onClick={() => setSelectedReport(type.id)}
                    >
                      <div className="rep-type-card-icon">{type.icon}</div>
                      <div className="rep-type-card-info">
                        <h4>{type.title}</h4>
                        <p>{type.desc}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* SECTION 2: SCOPE & FILTERS */}
              <div>
                <div className="rep-section-title"><IconFilter /> SCOPE & FILTERS</div>
                
                <div className="rep-form-row-3">
                  <div className="rep-form-group">
                    <label>Grade</label>
                    <select className="rep-input">
                      <option>All grades</option>
                      <option>Grade 10</option>
                    </select>
                  </div>
                  <div className="rep-form-group">
                    <label>Section</label>
                    <select className="rep-input">
                      <option>All sections</option>
                      <option>Section A</option>
                    </select>
                  </div>
                  <div className="rep-form-group">
                    <label>Subject</label>
                    <select className="rep-input">
                      <option>All subjects</option>
                      <option>Mathematics</option>
                    </select>
                  </div>
                </div>

                <div className="rep-form-row-3">
                  <div className="rep-form-group">
                    <label>Date from <span>*</span></label>
                    <input type="date" className="rep-input" defaultValue="2026-04-01" />
                  </div>
                  <div className="rep-form-group">
                    <label>Date to <span>*</span></label>
                    <input type="date" className="rep-input" defaultValue="2026-04-30" />
                  </div>
                  <div className="rep-form-group">
                    <label>Period preset</label>
                    <select className="rep-input">
                      <option>This month</option>
                      <option>Last month</option>
                      <option>This term</option>
                    </select>
                  </div>
                </div>

                <div className="rep-form-row-2">
                  <div className="rep-form-group">
                    <label>Teacher (if applicable)</label>
                    <select className="rep-input">
                      <option>All teachers</option>
                    </select>
                  </div>
                  <div className="rep-form-group">
                    <label>Student (for individual report)</label>
                    <div className="rep-input-icon-wrapper">
                      <IconSearch className="rep-input-icon" />
                      <input type="text" className="rep-input" placeholder="Leave blank for class-wide report" />
                    </div>
                  </div>
                </div>
              </div>

              {/* SECTION 3: OUTPUT FORMAT */}
              <div>
                <div className="rep-section-title"><IconFolder /> OUTPUT FORMAT & DELIVERY</div>
                
                <div className="rep-form-row-2">
                  <div className="rep-form-group">
                    <label>Export format <span>*</span></label>
                    <div className="rep-radio-group">
                      <label className="rep-radio-label" onClick={() => setExportFormat('PDF')}>
                        <input type="radio" name="format" checked={exportFormat === 'PDF'} readOnly />
                        <span className="rep-radio-circle"></span> PDF
                      </label>
                      <label className="rep-radio-label" onClick={() => setExportFormat('Excel')}>
                        <input type="radio" name="format" checked={exportFormat === 'Excel'} readOnly />
                        <span className="rep-radio-circle"></span> Excel
                      </label>
                      <label className="rep-radio-label" onClick={() => setExportFormat('CSV')}>
                        <input type="radio" name="format" checked={exportFormat === 'CSV'} readOnly />
                        <span className="rep-radio-circle"></span> CSV
                      </label>
                    </div>
                  </div>
                  <div className="rep-form-group">
                    <label>Report language</label>
                    <select className="rep-input">
                      <option>English</option>
                      <option>Urdu</option>
                    </select>
                  </div>
                </div>

                {/* Toggles */}
                <div className="rep-toggles-list">
                  <div className="rep-switch-row">
                    <div className="rep-switch-label">
                      <h4>Include school logo & header</h4>
                      <p>Adds EduSync school branding to the report</p>
                    </div>
                    <div className={`rep-toggle ${incLogo ? 'on' : ''}`} onClick={() => setIncLogo(!incLogo)}></div>
                  </div>
                  <div className="rep-switch-row">
                    <div className="rep-switch-label">
                      <h4>Include charts & visualizations</h4>
                      <p>Bar charts and trend graphs (PDF only)</p>
                    </div>
                    <div className={`rep-toggle ${incCharts ? 'on' : ''}`} onClick={() => setIncCharts(!incCharts)}></div>
                  </div>
                  <div className="rep-switch-row">
                    <div className="rep-switch-label">
                      <h4>Email report to admin</h4>
                      <p>Send generated report to admin@school.edu</p>
                    </div>
                    <div className={`rep-toggle ${emailAdmin ? 'on' : ''}`} onClick={() => setEmailAdmin(!emailAdmin)}></div>
                  </div>
                  <div className="rep-switch-row">
                    <div className="rep-switch-label">
                      <h4>Schedule recurring report</h4>
                      <p>Auto generate and email on a set schedule</p>
                    </div>
                    <div className={`rep-toggle ${schedRecurring ? 'on' : ''}`} onClick={() => setSchedRecurring(!schedRecurring)}></div>
                  </div>
                </div>
              </div>

              {/* SECTION 4: NOTES */}
              <div>
                <div className="rep-section-title"><IconNote /> ADDITIONAL NOTES</div>
                <div className="rep-form-group">
                  <textarea className="rep-input rep-textarea" placeholder="Any specific notes or instructions to include in the report header..."></textarea>
                </div>
              </div>

            </div>

            {/* Modal Footer */}
            <div className="rep-modal-footer">
              <div className="rep-req-text">* Reports are saved under Reports → Recent reports</div>
              <div className="rep-footer-actions">
                <button className="rep-btn-discard" onClick={() => setIsModalOpen(false)}>Cancel</button>
                <button className="rep-btn-preview">Preview report</button>
                <button className="rep-btn-publish" onClick={() => setIsModalOpen(false)}>
                  <IconRocket /> Generate report
                </button>
              </div>
            </div>

          </div>
        </div>
      )}

    </DashboardLayout>
  );
}